name: WordPress PHPCS

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          git clone -b develop https://github.com/WordPress/WordPress-Coding-Standards.git ~/wpcs
          ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/wpcs
          ~/.composer/vendor/bin/phpcs -i

      - name: Run PHPCS
        run: |
          ~/.composer/vendor/bin/phpcs --standard=WordPress ./
